// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neighborhood-flow/Confirm.tsx": () => import("../components/mockups/neighborhood-flow/Confirm.tsx"),
  "./components/mockups/neighborhood-flow/Generating.tsx": () => import("../components/mockups/neighborhood-flow/Generating.tsx"),
  "./components/mockups/neighborhood-flow/Landing.tsx": () => import("../components/mockups/neighborhood-flow/Landing.tsx"),
  "./components/mockups/neighborhood-flow/Login.tsx": () => import("../components/mockups/neighborhood-flow/Login.tsx"),
  "./components/mockups/neighborhood-flow/Report.tsx": () => import("../components/mockups/neighborhood-flow/Report.tsx"),
  "./components/mockups/neighborhood-flow/Settings.tsx": () => import("../components/mockups/neighborhood-flow/Settings.tsx"),
  "./components/mockups/streetwise-social/Instagram.tsx": () => import("../components/mockups/streetwise-social/Instagram.tsx"),
  "./components/mockups/streetwise-social/LinkedIn.tsx": () => import("../components/mockups/streetwise-social/LinkedIn.tsx"),
  "./components/mockups/streetwise-social/Story.tsx": () => import("../components/mockups/streetwise-social/Story.tsx"),
  "./components/mockups/streetwise-social/TwitterCard.tsx": () => import("../components/mockups/streetwise-social/TwitterCard.tsx"),
  "./components/mockups/streetwise-waitlist/Waitlist.tsx": () => import("../components/mockups/streetwise-waitlist/Waitlist.tsx")
};
