// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neighborhood-flow/Confirm.tsx": () => import("../components/mockups/neighborhood-flow/Confirm.tsx"),
  "./components/mockups/neighborhood-flow/Generating.tsx": () => import("../components/mockups/neighborhood-flow/Generating.tsx"),
  "./components/mockups/neighborhood-flow/Landing.tsx": () => import("../components/mockups/neighborhood-flow/Landing.tsx"),
  "./components/mockups/neighborhood-flow/Report.tsx": () => import("../components/mockups/neighborhood-flow/Report.tsx")
};
